name: mi-app-estatica
services:
  - name: web
    static_sites:
      build_command: ""
      output_dir: "."
    source:
      type: github
      repo: AlexTestz/Hola_Mundo_En_Html
      branch: main
