name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main   # o la rama que uses (por ejemplo "master")
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Si solo es HTML estático, no necesitas build, sino solo subir la carpeta raíz o donde esté el index.html.
      # Cambia './dist' por el folder correcto (por ejemplo '.' si está en la raíz)
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: '.'  # carpeta raíz con tu index.html
          production-branch: main  # rama principal de tu repo
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy desde GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5